## Lecture 01 - Introduction to NumPy and Shape Analysis

### Why NumPy?

Images contain millions of pixels. Processing them using pure Python loops is highly inefficient because Python processes each element sequentially with massive overhead. **NumPy (Numeric Python)** provides **vectorization**, allowing us to perform mathematical operations on entire arrays simultaneously at C-speed without writing loops.

---

In [1]:
import numpy as np
import time

# ---------------------------------------------------------
# 1. Comparing Pure Python Loops vs. NumPy Vectorization
# ---------------------------------------------------------

# Generate 10 million random pixel intensity values
size = 10_000_000
xs = np.random.rand(size) # Vectorized generation

# Benchmark Pure Python Loop
start_time = time.time()
ys_python = []
for x in xs:
    ys_python.append(3 * x + 4) # Applying y = 3x + 4 sequentially
python_duration = time.time() - start_time

# Benchmark NumPy Vectorization
start_time = time.time()
ys_numpy = xs * 3 + 4 # Applying y = 3x + 4 in parallel across the entire array
numpy_duration = time.time() - start_time

print(f"Python Loop Time: {python_duration:.4f} seconds")
print(f"NumPy Vectorized Time: {numpy_duration:.4f} seconds")
print(f"NumPy is roughly {python_duration / numpy_duration:.1f}x faster!")

Python Loop Time: 1.5233 seconds
NumPy Vectorized Time: 0.0294 seconds
NumPy is roughly 51.8x faster!


---

### Understanding Array Creation: Python Lists vs. NumPy Arrays

A standard Python list performs element concatenation when using the `+` operator, whereas a NumPy array performs actual element-wise addition.

In [2]:
# Standard Python Lists
a_list = [3, 4, 5]
b_list = [6, 7, 8]
print(f"Original Python List Addition: {a_list + b_list}") # Concatenates

# NumPy Arrays
a_arr = np.array(a_list)
b_arr = np.array(b_list)
print(f"Updated NumPy Array Addition: {a_arr + b_arr}") # Element-wise sum


Original Python List Addition: [3, 4, 5, 6, 7, 8]
Updated NumPy Array Addition: [ 9 11 13]


---

### Reading and Interpreting Tensor Shapes

In machine learning frameworks, data matrices are called **Tensors**. To read an image tensor shape, evaluate the dimensions from left to right:

* **3D Tensor Structure:** `(Channels, Height, Width)` $\rightarrow$ `Channels=3` for RGB images, and `Channels=1` for Grayscale images.
* **4D Tensor Structure:** `(Batch_Dim, Channels, Height, Width)` $\rightarrow$ The first dimension always indicates the number of images processed together in a single batch.

In [3]:
# ---------------------------------------------------------
# 2. Analyzing Multi-Dimensional Tensor Shapes
# ---------------------------------------------------------

# Generate a mock batch of 4 RGB images, each with a size of 2x2 pixels
# Shape layout: [Batch_Size, Channels, Height, Width]
batch_of_images = np.random.randint(0, 10, (4, 3, 2, 2))

print(f"Full Batch Tensor Shape: {batch_of_images.shape}")
print(f"Total Dimensions: {batch_of_images.ndim}")
print(f"First Dimension (Batch Size): {batch_of_images.shape[0]}")

print("\n--- Accessing Individual Image Tensors inside the Batch ---")
print(f"Image 1 Shape: {batch_of_images[0].shape}") # Yields the (C, H, W) of index 0
print(f"Image 2 Shape: {batch_of_images[1].shape}")

Full Batch Tensor Shape: (4, 3, 2, 2)
Total Dimensions: 4
First Dimension (Batch Size): 4

--- Accessing Individual Image Tensors inside the Batch ---
Image 1 Shape: (3, 2, 2)
Image 2 Shape: (3, 2, 2)


### Day 2 — Common Array Initializers in NumPy

NumPy provides native functions to instantly construct arrays with specific shapes and default value configurations without writing standard loop boilerplate.

In [4]:
import numpy as np

# 1. Constant Value Initializations
zeros_mat = np.zeros(shape=(3, 3))            # 3x3 Matrix filled with 0.0
ones_mat = np.ones(shape=(2, 2))              # 2x2 Matrix filled with 1.0 (often used for gradient masking)
five_mat = np.full(shape=(2, 2), fill_value=5) # 2x2 Matrix filled with a custom target value (5)
identity_mat = np.eye(3)                      # 3x3 Identity Matrix with diagonal 1s

# 2. Random Distribution Generators
rand_uniform = np.random.rand(3, 4)           # Uniformly distributed values between [0, 1)
rand_normal = np.random.randn(3, 4)           # Standard Normal distribution (Mean = 0, Std = 1)

print("--- Distribution Analysis Check ---")
print(f"Uniform distribution -> Mean: {rand_uniform.mean():.2f} | Std: {rand_uniform.std():.2f}")
print(f"Normal distribution  -> Mean: {rand_normal.mean():.2f} | Std: {rand_normal.std():.2f}\n")

# 3. Step and Interval Sequences
step_range = np.arange(start=13, stop=50, step=2)  # Generates odd numbers up to (but excluding) 50
linear_space = np.linspace(start=0, stop=1, num=5) # 5 evenly spaced numbers dividing the range [0, 1]

print(f"arange sequence: {step_range}")
print(f"linspace divisions: {linear_space}")

--- Distribution Analysis Check ---
Uniform distribution -> Mean: 0.57 | Std: 0.28
Normal distribution  -> Mean: -0.42 | Std: 1.06

arange sequence: [13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49]
linspace divisions: [0.   0.25 0.5  0.75 1.  ]


#### Dimensionality Nomenclature: Physics vs. Machine Learning

To maintain absolute structural clarity, machine learning drops classic descriptive terms like *scalar*, *vector*, or *matrix* and classifies arrays strictly by their total coordinate axes as **$n$-Dimensional Tensors**.

| Physical Data Structure | Deep Learning Tensor Convention |
| :--- | :--- |
| `3` (Single Scalar) | **0D Tensor** |
| `[3, 4]` (1D Array/Vector) | **1D Tensor** |
| `[[1, 2], [5, 3]]` (2D Grid/Matrix) | **2D Tensor** |
| `[[[4, 2], [3, 1]], [[6, 2], [7, -2]]]` (3D Volume) | **3D Tensor** |

In [5]:
# Verifying dimensions (.ndim) using Machine Learning tensor conventions
tensor_4d = np.random.rand(2, 3, 4, 5) # 4D Tensor (e.g., Image Batches)
tensor_3d = np.random.rand(2, 3, 4)    # 3D Tensor (e.g., Sequence/Text Embeddings)
tensor_2d = np.random.rand(2, 3)       # 2D Tensor (e.g., Tabular Rows/Features)
tensor_1d = np.random.rand(3)          # 1D Tensor (e.g., Layer Biases)
scalar_0d = np.array(3)                # 0D Tensor (e.g., Evaluation Metrics / Total Loss)

print(f"tensor_4d dimensions: {tensor_4d.ndim}-D")
print(f"tensor_3d dimensions: {tensor_3d.ndim}-D")
print(f"tensor_2d dimensions: {tensor_2d.ndim}-D")
print(f"tensor_1d dimensions: {tensor_1d.ndim}-D")
print(f"scalar_0d dimensions: {scalar_0d.ndim}-D")

tensor_4d dimensions: 4-D
tensor_3d dimensions: 3-D
tensor_2d dimensions: 2-D
tensor_1d dimensions: 1-D
scalar_0d dimensions: 0-D


#### Core Tensor Inspection Properties

Before passing data tensors into deep learning layers, we must inspect their shapes, structural volume, and data storage types to avoid tensor incompatibility runtime errors.

In [6]:
# Sample 3D Tensor initialization
sample_tensor = np.random.randint(0, 10, size=(1, 5, 6))

# Essential metadata retrieval attributes
print(f"1. .shape : {sample_tensor.shape}") # Dimensions layout configuration
print(f"2. .ndim  : {sample_tensor.ndim}")  # Absolute number of data axes
print(f"3. .size  : {sample_tensor.size}")  # Multiplied total number of individual elements (1 * 5 * 6)
print(f"4. .dtype : {sample_tensor.dtype}") # Memory data type block (e.g., int32, float64)

1. .shape : (1, 5, 6)
2. .ndim  : 3
3. .size  : 30
4. .dtype : int32


#### Fundamental Shape Transformations

Modifying the shape of an array is a routine operation in image processing. NumPy allows us to adjust array dimensions, flatten multidimensional matrices, or compute matrix transposes.

In [7]:
# Create a baseline 1D vector of 6 elements
base_vector = np.array([1, 2, 3, 4, 5, 6])
print(f"Original 1D Vector: {base_vector} | Shape: {base_vector.shape}\n")

# 1. Reshaping (Altering layout without changing underlying element count)
reshaped_matrix = base_vector.reshape(2, 3)
print("--- After .reshape(2, 3) ---")
print(reshaped_matrix)
print(f"New Matrix Shape: {reshaped_matrix.shape}\n")

# 2. Transposition (Swapping rows with columns)
transposed_matrix = reshaped_matrix.T
print("--- After .T (Transpose) ---")
print(transposed_matrix)
print(f"Transposed Shape: {transposed_matrix.shape}\n")

# 3. Flattening (Collapsing multi-dimensional structures back into a 1D vector)
flattened_vector = transposed_matrix.flatten()
print("--- After .flatten() ---")
print(flattened_vector)
print(f"Flattened Shape: {flattened_vector.shape}")

Original 1D Vector: [1 2 3 4 5 6] | Shape: (6,)

--- After .reshape(2, 3) ---
[[1 2 3]
 [4 5 6]]
New Matrix Shape: (2, 3)

--- After .T (Transpose) ---
[[1 4]
 [2 5]
 [3 6]]
Transposed Shape: (3, 2)

--- After .flatten() ---
[1 4 2 5 3 6]
Flattened Shape: (6,)


### Day 3 — Array Operations and Broadcasting

Today we transition from static shape analysis to dynamic array manipulation. We will cover:
1. **Indexing and Slicing:** Extracting sub-grids, rows, columns, and target pixel patches from multi-dimensional arrays.
2. **Element-wise Operations:** Performing vectorized math seamlessly across matching matrices.
3. **Broadcasting:** Understanding the core rules that allow NumPy to perform arithmetic on arrays with different but compatible shapes.

#### 1. Indexing and Slicing

Slicing allows you to target specific coordinates or sub-regions within a tensor without making memory copies. NumPy uses the `[start:stop:step]` syntax across multiple dimensions separated by commas: `[row_slice, column_slice]`.

### 2. Element-wise Operations

When two tensors share the exact same dimensions, any standard arithmetic operator (`+`, `-`, `*`, `/`) automatically executes element-by-element across matching indices in parallel.

#### 3. Broadcasting Rules

Broadcasting solves a massive architectural problem: **How do we perform arithmetic operations on arrays of different shapes?** Instead of writing a performance-killing Python loop to replicate data manually, NumPy evaluates your tensor dimensions from right to left (trailing dimensions). Two dimensions are compatible if:
1. They are **equal**, OR
2. One of them is **exactly 1**.

If compatible, NumPy virtually stretches the smaller dimension to fit the larger one without allocating extra physical hardware memory.

### Day 4 — Vectorization
<!-- np.sum()
np.mean()
np.max()
np.min()
np.argmax()
np.exp()
np.log()
np.sqrt() -->

### Day 4 — Linear Algebra for ML
1. Dot Product
2. Matrix Multiplication
3. Cross Product
4. Useful Linear Algebra Functions
    <!-- np.linalg.norm()
    np.linalg.inv()
    np.linalg.det()
    np.linalg.eig() -->

In [8]:
# np.zeros((3, 3))
# np.ones((2, 2))
# np.full((2, 2), 5)
# np.eye(3)
# np.random.randn(3, 4)
# np.arange(10)
# np.linspace(0, 1, 5)

# a.shape
# a.ndim
# a.size
# a.dtype

# a.reshape(2, 3)
# a.flatten()
# a.T