## Lecture 01 - Introduction to NumPy and Shape Analysis

### Why NumPy?

Images contain millions of pixels. Processing them using pure Python loops is highly inefficient because Python processes each element sequentially with massive overhead. **NumPy (Numeric Python)** provides **vectorization**, allowing us to perform mathematical operations on entire arrays simultaneously at C-speed without writing loops.

---

In [1]:
import numpy as np
import time

# ---------------------------------------------------------
# 1. Comparing Pure Python Loops vs. NumPy Vectorization
# ---------------------------------------------------------

# Generate 10 million random pixel intensity values
size = 10_000_000
xs = np.random.rand(size) # Vectorized generation

# Benchmark Pure Python Loop
start_time = time.time()
ys_python = []
for x in xs:
    ys_python.append(3 * x + 4) # Applying y = 3x + 4 sequentially
python_duration = time.time() - start_time

# Benchmark NumPy Vectorization
start_time = time.time()
ys_numpy = xs * 3 + 4 # Applying y = 3x + 4 in parallel across the entire array
numpy_duration = time.time() - start_time

print(f"Python Loop Time: {python_duration:.4f} seconds")
print(f"NumPy Vectorized Time: {numpy_duration:.4f} seconds")
print(f"NumPy is roughly {python_duration / numpy_duration:.1f}x faster!")

Python Loop Time: 2.5458 seconds
NumPy Vectorized Time: 0.0632 seconds
NumPy is roughly 40.3x faster!


---

### Understanding Array Creation: Python Lists vs. NumPy Arrays

A standard Python list performs element concatenation when using the `+` operator, whereas a NumPy array performs actual element-wise addition.

In [2]:
# Standard Python Lists
a_list = [3, 4, 5]
b_list = [6, 7, 8]
print(f"Original Python List Addition: {a_list + b_list}") # Concatenates

# NumPy Arrays
a_arr = np.array(a_list)
b_arr = np.array(b_list)
print(f"Updated NumPy Array Addition: {a_arr + b_arr}") # Element-wise sum


Original Python List Addition: [3, 4, 5, 6, 7, 8]
Updated NumPy Array Addition: [ 9 11 13]


---

### Reading and Interpreting Tensor Shapes

In machine learning frameworks, data matrices are called **Tensors**. To read an image tensor shape, evaluate the dimensions from left to right:

* **3D Tensor Structure:** `(Channels, Height, Width)` $\rightarrow$ `Channels=3` for RGB images, and `Channels=1` for Grayscale images.
* **4D Tensor Structure:** `(Batch_Dim, Channels, Height, Width)` $\rightarrow$ The first dimension always indicates the number of images processed together in a single batch.

In [3]:
# ---------------------------------------------------------
# 2. Analyzing Multi-Dimensional Tensor Shapes
# ---------------------------------------------------------

# Generate a mock batch of 4 RGB images, each with a size of 2x2 pixels
# Shape layout: [Batch_Size, Channels, Height, Width]
batch_of_images = np.random.randint(0, 10, (4, 3, 2, 2))

print(f"Full Batch Tensor Shape: {batch_of_images.shape}")
print(f"Total Dimensions: {batch_of_images.ndim}")
print(f"First Dimension (Batch Size): {batch_of_images.shape[0]}")

print("\n--- Accessing Individual Image Tensors inside the Batch ---")
print(f"Image 1 Shape: {batch_of_images[0].shape}") # Yields the (C, H, W) of index 0
print(f"Image 2 Shape: {batch_of_images[1].shape}")

Full Batch Tensor Shape: (4, 3, 2, 2)
Total Dimensions: 4
First Dimension (Batch Size): 4

--- Accessing Individual Image Tensors inside the Batch ---
Image 1 Shape: (3, 2, 2)
Image 2 Shape: (3, 2, 2)


### Day 2 — Array Operations and Broadcasting

1. Indexing and Slicing
2. Element-wise Operations
3. Broadcasting

In [ ]:
a = np.zeros(shape = (3, 3))
b = np.ones(shape = (2, 2)) # usually used to backpropogate throught Loss function
c = np.full(shape = (2, 2), fill_value = 5)
d = np.eye(3) # 3x3 Identity Matrix
e = np.random.rand(3, 4) # random n number
f = np.random.randn(3, 4) # random n numbers with mean = 0, std = 1
print(f"e.mean() = {e.mean()} | e.std() = {e.std()}")
print(f"f.mean() = {f.mean()} | f.std() = {f.std()}")
g = np.arange(start = 13, stop = 50, step = 2)
h = np.linspace(0, 1, 5)

e.mean() = 0.5461047529233045 | e.std() = 0.30046913545836107
f.mean() = 0.007287485793794425 | f.std() = 0.8001669273311576


In [ ]:
# scalar and vectors
# Tensors, 3

In [62]:
# Physics and Maths Convention

# [3] --> Scalar
# [3, 4] --> Vector
# [[1, 2] , [5, 3]] --> Matrix
# [[[4, 2] , [3, 1]], [[6, 2] , [7, -2]]] --> Tensor


# Machine Learning Convention
# [3] / 3 --> 0D - Tensor
# [3, 4] --> 1D - Tensor
# [[1, 2] , [5, 3]] --> 2D - Tensor
# [[[4, 2] , [3, 1]], [[6, 2] , [7, -2]]] --> 3D+ Tensor

In [92]:
a = np.random.rand(2, 3, 4, 5) # 4-D
b = np.random.rand(2, 3, 4) # 3-D
c = np.random.rand(2, 3) # 2-D
d = np.random.rand(3) # 1-D
e = 3 # 0-D Tensor
print(f"a.ndim = {a.ndim}")
print(f"b.ndim = {b.ndim}")
print(f"c.ndim = {c.ndim}")
print(f"d.ndim = {d.ndim}")
print(f"e.ndim = {0}")

f = np.random.rand(3, 3) # f is a 2-D Tensor having shape = (3,3) || rather than saying, f is a 3x3 Matrix
g = np.random.rand(1, 5, 6) # g is a 3-D Tensor having shape = (1, 5, 6) and we can check the shape as g.shape
# and we can check number of elements as g.size

a.ndim = 4
b.ndim = 3
c.ndim = 2
d.ndim = 1
e.ndim = 0


In [108]:
ep = np.random.rand(3, 2, 5)
ep

array([[[0.28129219, 0.06650218, 0.80642326, 0.28249087, 0.81363716],
        [0.00614044, 0.20179397, 0.49282375, 0.17572863, 0.53224514]],

       [[0.85536163, 0.23173314, 0.86317409, 0.31827301, 0.47754905],
        [0.61378173, 0.78214605, 0.5525914 , 0.07146567, 0.93144255]],

       [[0.04183401, 0.92834153, 0.00770186, 0.33452418, 0.7714356 ],
        [0.08301519, 0.54088343, 0.82773422, 0.4901833 , 0.13733705]]])

In [122]:
eps = np.random.randint(0, 10, (2, 3))
eps

array([[3, 7, 7],
       [3, 3, 9]], dtype=int32)

In [93]:
g

array([[[0.16080547, 0.64580692, 0.37506152, 0.12144622, 0.55767681,
         0.09335119],
        [0.25270087, 0.65038692, 0.75202647, 0.27698447, 0.29294429,
         0.82329311],
        [0.8556944 , 0.84495324, 0.65941401, 0.93806919, 0.33979291,
         0.27956087],
        [0.67451243, 0.57879263, 0.21065507, 0.16747134, 0.55668271,
         0.66079661],
        [0.27848279, 0.48532372, 0.52461069, 0.97460117, 0.47201582,
         0.29627472]]])

In [94]:
g.dtype

dtype('float64')

In [74]:
d

array([0.18485462, 0.71406405, 0.03132441])

In [73]:
c

array([[0.63836057, 0.56981462, 0.51155724],
       [0.24430926, 0.3507692 , 0.3930894 ]])

### Day 3 — Vectorization
<!-- np.sum()
np.mean()
np.max()
np.min()
np.argmax()
np.exp()
np.log()
np.sqrt() -->

### Day 4 — Linear Algebra for ML
1. Dot Product
2. Matrix Multiplication
3. Cross Product
4. Useful Linear Algebra Functions
    <!-- np.linalg.norm()
    np.linalg.inv()
    np.linalg.det()
    np.linalg.eig() -->

In [4]:
# np.zeros((3, 3))
# np.ones((2, 2))
# np.full((2, 2), 5)
# np.eye(3)
# np.random.randn(3, 4)
# np.arange(10)
# np.linspace(0, 1, 5)

# a.shape
# a.ndim
# a.size
# a.dtype

# a.reshape(2, 3)
# a.flatten()
# a.T