### Matrix Calculus

In [58]:
import numpy as np
X = np.random.randint(0, 10, (2, 2))
W = np.random.randint(0, 10, (2, 2))
b = np.random.randint(0, 10, (2,))

In [59]:
X # input to the model

array([[5, 3],
       [4, 7]], dtype=int32)

In [60]:
W, b # Learnable parameters

(array([[7, 4],
        [2, 1]], dtype=int32),
 array([6, 5], dtype=int32))

In [ ]:
y = X @ W + b
y_true = np.random.randint(0, 10, y.shape)
# mse_loss = ((y_true - y) ** 2) / len(y_true) # This is not what we will use (it's homework for you)
loss = y.sum()
dL_dy = np.ones_like(y)

In [ ]:
def compute_gradients(X, dL_dy):
    dL_dW = X.T @ dL_dy
    # dL_dX = dL_dy @ W.T
    dL_db = dL_dy.sum(axis = 1)
    return dL_dW, dL_db

def perform_gradient_descent(W, b, dL_dW, dL_db, lr = 0.01):
    # --------------- Gradient Descent --------------- 
    lr = 0.01
    W = W - dL_dW * lr
    b = b - dL_db * lr
    return W, b

def predict(X, W, b):
    return X @ W + b

for i in range(100):
    dL_dW, dL_db = compute_gradients(X, dL_dy)
    W, b = perform_gradient_descent(W, b, dL_dW, dL_db)

    if i % 30 == 0:
        y = predict(X, W, b)
        loss = y.sum()
        print(f"[epoch = {i} / {100}] | Loss = {loss:.3f}")


[epoch = 0 / 100] | Loss = 147.300
[epoch = 30 / 100] | Loss = 36.300
[epoch = 60 / 100] | Loss = -74.700
[epoch = 90 / 100] | Loss = -185.700
