### Matrix Calculus

In [1]:
import numpy as np
X = np.random.randint(0, 10, (2, 2))
W = np.random.randint(0, 10, (2, 2))
b = np.random.randint(0, 10, (2,))

In [2]:
X # input to the model

array([[0, 1],
       [1, 1]], dtype=int32)

In [3]:
W, b # Learnable parameters

(array([[1, 6],
        [2, 6]], dtype=int32),
 array([3, 5], dtype=int32))

In [4]:
y = X @ W + b
y_true = np.random.randint(0, 10, y.shape)
# mse_loss = ((y_true - y) ** 2) / len(y_true) # This is not what we will use (it's homework for you)
loss = y.sum()
dL_dy = np.ones_like(y)

In [135]:
def compute_gradients(X, dL_dy):
    dL_dW = X.T @ dL_dy
    # dL_dX = dL_dy @ W.T
    dL_db = dL_dy.sum(axis = 1)
    return dL_dW

def perform_gradient_descent(W, b, dL_dW, dL_db, lr = 0.01):
    # --------------- Gradient Descent --------------- 
    lr = 0.01
    W = W - dL_dW * lr
    # b = b - dL_db * lr
    return W

def predict(X, W, b):
    return X @ W + b

for i in range(100):
    dL_dW, dL_db = compute_gradients(X, dL_dy)
    W, b = perform_gradient_descent(W, b, dL_dW, dL_db)

    if i % 30 == 0:
        y = predict(X, W, b)
        loss = y.sum()
        print(f"[epoch = {i} / {100}] | Loss = {loss:.3f}")


ValueError: too many values to unpack (expected 2)

In [149]:
X = np.random.rand(2, 5)
W = np.random.rand(5, 1)
# b = np.random.rand(2,1)
y_true = np.array([5, -1]).reshape(2, 1)
y_p = X @ W


# Compute Loss
loss_fn = (np.sum((y_true - y_p) ** 2)) / len(y_p)
dL_dy = (-2 / (len(y_p))) * (y_true - y_p)

In [150]:
y_true.shape, y_p.shape

((2, 1), (2, 1))

In [151]:
X.shape, W.shape, b.shape

((2, 5), (5, 1), (2, 2))

In [152]:
dL_dy.shape

(2, 1)

In [154]:
print(f"X = {X}")
print("-" * 100)
print(f"W = {W}")
print("-" * 100)
print(f"b = {b}")
print("-" * 100)
print(f"y_predictions = {y_p}")
print("-" * 100)
print(f"y_true = {y_true}")
print("-" * 100)
print(f"dL/dy_p = {dL_dy}")
print("-" * 100)
dL_dW = compute_gradients(X, dL_dy)
print(f"dL/dW = {dL_dW}")
print("-" * 100)
# print(f"dL/db = {dL_db}")
print("-" * 100)

X = [[0.52250587 0.31005179 0.9902399  0.67278035 0.64225289]
 [0.9285957  0.40827516 0.97971683 0.65740041 0.50946223]]
----------------------------------------------------------------------------------------------------
W = [[0.44681398]
 [0.27740386]
 [0.52651961]
 [0.88588545]
 [0.53362178]]
----------------------------------------------------------------------------------------------------
b = [[1.00284901 0.95009562]
 [0.61969286 0.56693946]]
----------------------------------------------------------------------------------------------------
y_predictions = [[1.77957968]
 [1.89824837]]
----------------------------------------------------------------------------------------------------
y_true = [[ 5]
 [-1]]
----------------------------------------------------------------------------------------------------
dL/dy_p = [[-3.22042032]
 [ 2.89824837]]
----------------------------------------------------------------------------------------------------
dL/dW = [[ 1.00861247]
 [ 0.1847857

In [ ]:
import numpy as np
X = np.random.rand(2, 5)
W = np.random.rand(5, 1)
bias = np.random.rand(1,)
y_true = np.array([5, -1]).reshape(2, 1)
print(f"Original Predictions: {X @ W + bias}")
# print(f"Original Predictions: {X @ W}")
print("-" * 100)
print(f"True Targets: {y_true}")
print("-" * 100)
for i in range(10000):
    y_p = X @ W + bias # issue [node-2]                     <-------------- Forward pass
    # print(f"y_p.shape = {y_p.shape}")
    # y_p = X @ W
    loss_fn = (np.sum((y_true - y_p) ** 2)) / len(y_p)

    # -------------------------- Backward pass [Starts] ---------------------------
    dL_dy = (-2 / (len(y_p))) * (y_true - y_p) # Issue [node-1]
    # print(f"dL_dy.shape = {dL_dy.shape}")
    dL_dW = X.T @ dL_dy
    # print(f"dL_dW.shape = {dL_dW.shape}")
    dL_db = dL_dy.sum() # issue [node-3]
    # -------------------------- Backward pass [Ends] ------------------------------

    # print(f"dL_db.shape = {dL_db.shape}")
    # ------------------------- Optimizers starts -------------------------------
    W = W - 0.01 * dL_dW
    bias = bias - 0.01 * dL_db # issue [node-4]
    # ------------------------- Optimizers ends -------------------------------
    # print(f"updated_bias.shape = {bias.shape}")

    if i % 1000 == 0:
        print(f"Epochs [{i}/{10000}] | Loss = {loss_fn}")

print("-" * 100)
print(f"Final Predictions: {X @ W + bias}")


Original Predictions: [[1.80986393]
 [1.6532302 ]]
----------------------------------------------------------------------------------------------------
True Targets: [[ 5]
 [-1]]
----------------------------------------------------------------------------------------------------
Epochs [0/10000] | Loss = 8.608299317104024
Epochs [1000/10000] | Loss = 0.000670657416948188
Epochs [2000/10000] | Loss = 5.2572358330885286e-08
Epochs [3000/10000] | Loss = 4.12110980581751e-12
Epochs [4000/10000] | Loss = 3.230508861808418e-16
Epochs [5000/10000] | Loss = 2.5323344049252042e-20
Epochs [6000/10000] | Loss = 1.9873029345459538e-24
Epochs [7000/10000] | Loss = 1.8564115771146342e-27
Epochs [8000/10000] | Loss = 1.2918645028883815e-27
Epochs [9000/10000] | Loss = 1.2177054148217843e-27
----------------------------------------------------------------------------------------------------
Final Predictions: [[ 5.]
 [-1.]]


In [ ]:
class LinearLayer:
    def __init__(self):
        pass

    def forward(self, x):
        pass

    def backward(self, out_grad):
        pass

# class Optimizer:
#     def __init__(self):
#         pass

#     def step(self, x):
#         pass

#     def zero_grad(self):
#         pass

In [10]:
bias.shape, dL_db.shape, dL_dy.shape, y_p.shape, W.shape, dL_dW.shape, X.shape

((1,), (), (2, 1), (2, 1), (5, 1), (5, 1), (2, 5))

In [11]:
y_true

array([[ 5],
       [-1]])

In [12]:
X_test = np.random.rand(1, 5)
X_test

array([[0.61109904, 0.80404741, 0.93026731, 0.02715037, 0.8018682 ]])

In [13]:
X_test @ W

array([[4.13658121]])