## Practical Exercises: Array Initializers, Shape Analysis, and Reshaping

### Directions
1. Insert a new code cell directly below each question block.
2. Write your programmatic solution inside that new cell.
3. Verify that your code executes cleanly without runtime dimension mismatch errors.

In [11]:
# ==============================================================================================
# QUESTION 1: Matrix Blank Canvas Initialization
# ----------------------------------------------------------------------------------------------
# Task: Create a 5x5 matrix filled entirely with zeros, then change the central element to 1.
#
# Requirements:
# 1. Initialize a 2D NumPy array named `canvas` of shape (5, 5) using `np.zeros`.
# 2. Use explicit 2D indexing to modify the exact middle element (row index 2, column index 2) to 1.0.
# 3. Print the matrix and verify its shape using `.shape`.
# ==============================================================================================

# Write your solution in a new cell below this one

In [3]:
%pip install numpy


Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 5.3 MB 3.4 MB/s eta 0:00:01
You should consider upgrading via the '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

canvas= np.zeros(shape=(5,5))
canvas[2][2]=1
print(canvas,f"\n shape is: {canvas.shape}")


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 
 shape is: (5, 5)


In [5]:
# ==============================================================================================
# QUESTION 2: Normal Distribution Variance Verification
# ----------------------------------------------------------------------------------------------
# Task: Generate random numbers from a standard normal distribution and inspect its properties.
#
# Requirements:
# 1. Generate a 2D tensor of shape (50, 50) containing random numbers with mean=0 and std=1.
#    (Hint: use `np.random.randn`).
# 2. Compute and print the empirical mean using `.mean()`.
# 3. Compute and print the empirical standard deviation using `.std()`.
# 4. Write a brief comment explaining why the printed mean is close to, but not exactly, 0.0.
# ==============================================================================================

# Write your solution in a new cell below this one

In [8]:
import numpy as np

a= np.random.randn(50,50)
print(f"Mean: {a.mean()}")
print(f"Standard Deviation: {a.std()}")


Mean: -0.023873664880884535
Standard Deviation: 0.9857131878806575


In [13]:
# ==============================================================================================
# QUESTION 3: Even Interval Generation via linspace
# ----------------------------------------------------------------------------------------------
# Task: Generate an array of evenly spaced numbers acting as thresholds between 0 and 5.
#
# Requirements:
# 1. Use `np.linspace` to create an array named `thresholds` containing exactly 11 elements 
#    equally dividing the range from 0.0 to 5.0 (inclusive).
# 2. Print the array.
# 3. Print the distance between any two adjacent elements to confirm the spacing is perfectly linear.
# ==============================================================================================

# Write your solution in a new cell below this one

In [10]:
import numpy as np

thresholds = np.linspace(start= 0.0,stop=5.0, num=11)
print(thresholds)
print(f"Spaces= {thresholds.std()}")
print(f"Spaces bw first two elements= {thresholds[1]-thresholds[0]}")
print(f"Spaces bw second two elements= {thresholds[2]-thresholds[1]}")


[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
Spaces= 1.5811388300841898
Spaces bw first two elements= 0.5
Spaces bw second two elements= 0.5


In [14]:
# ==============================================================================================
# QUESTION 4: Mathematical Elements Volume Audit
# ----------------------------------------------------------------------------------------------
# Task: Extract structural size attributes from a high-dimensional machine learning tensor.
#
# Requirements:
# 1. Initialize a 4D random uniform tensor named `activation_map` with shape (16, 3, 32, 32).
# 2. Print its total number of axes using `.ndim`.
# 3. Print its total element count volume using `.size`.
# 4. Programmatically calculate and print the expected size by multiplying the shape dimensions together.
# ==============================================================================================

# Write your solution in a new cell below this one

In [11]:

activation_map= np.random.rand(16,3,32,32)
print(f"total number of axes: {activation_map.ndim}")
print(f"total element count volume: {activation_map.size}")
print(f"size: {16*3*32*32}")

total number of axes: 4
total element count volume: 49152
size: 49152


In [15]:
# ==============================================================================================
# QUESTION 5: Reshaping Safety Laws & Total Count Invariance
# ----------------------------------------------------------------------------------------------
# Task: Intentionally trigger a common shape allocation mistake to understand how NumPy protects memory.
#
# Requirements:
# 1. Create a 1D vector containing numbers from 1 to 12 using `np.arange`.
# 2. Use a `try-except` code block to attempt reshaping this 12-element vector into a 3x5 matrix.
# 3. Catch the `ValueError` runtime exception and print the exact error message generated by NumPy.
# 4. Inside the same block, successfully reshape it into a valid 3x4 matrix and print the outcome.
# ==============================================================================================

# Write your solution in a new cell below this one

In [ ]:
#out of syllabus

In [16]:
# ==============================================================================================
# QUESTION 6: Automatic Dimension Calculation with Wildcard -1
# ----------------------------------------------------------------------------------------------
# Task: Use NumPy's automated dimension solving feature to reshape a flat image sequence.
#
# Requirements:
# 1. Create a large flat vector of 1000 random pixel values.
# 2. Reshape this vector into a 2D matrix where you explicitly set the row dimension to 40, 
#    and pass `-1` as the column dimension.
# 3. Print the resulting array shape and write a short comment explaining how NumPy calculated 
#    the hidden column dimension.
# ==============================================================================================

# Write your solution in a new cell below this one

In [12]:
v= np.random.rand(1000)
v.reshape(40,-1)
print(f"shape: {v.shape}")

shape: (1000,)


In [17]:
# ==============================================================================================
# QUESTION 7: The Flatten vs. Transpose Ordering Trap
# ----------------------------------------------------------------------------------------------
# Task: Examine how row-major structuring alters data layout ordering during unrolling.
#
# Requirements:
# 1. Manually build this specific 2x3 matrix:
#    M = np.array([[1, 2, 3], 
#                  [4, 5, 6]])
# 2. Run `.flatten()` directly on `M` and print the result.
# 3. Run `.flatten()` on its transpose `M.T` and print the result.
# 4. Write a comment stating whether the outputs match and why the order changed.
# ==============================================================================================

# Write your solution in a new cell below this one

In [ ]:
M = np.array([[1, 2, 3], 
                  [4, 5, 6]])
print(M.flatten())
print(M.T.flatten())
# the outputs wont match because when we transpose the rows and columns of a matrix interchanges therefore 
# the order of the flattened matrix changes


[1 2 3 4 5 6]
[1 4 2 5 3 6]


In [15]:
# ==============================================================================================
# QUESTION 8: Multi-Channel Tensor Unrolling
# ----------------------------------------------------------------------------------------------
# Task: Take a mock 3D image block representation and flatten it without modifying the original array.
#
# Requirements:
# 1. Construct a mock image tensor of shape (3, 4, 4) filled with random integers between 0 and 9.
#    (3 color channels, 4x4 spatial pixel resolution).
# 2. Unroll this multi-dimensional array into a simple continuous 1D line using `.flatten()`.
# 3. Print the shape of the flattened array.
# 4. Print the shape of the original tensor to prove that flattening creates a transformation 
#    without destroying the original tensor layout geometry.
# ==============================================================================================

# Write your solution in a new cell below this one

In [26]:
images= np.random.randint(0,9,size= (3,4,4))
images.flatten()
print(f"shape: {images.shape}")
print("shape of original shape: (3,4,4)")

shape: (3, 4, 4)
shape of original shape: (3,4,4)


In [19]:
# ==============================================================================================
# QUESTION 9: Creating Column Vectors for Weight Calculations
# ----------------------------------------------------------------------------------------------
# Task: Turn a standard flat 1D vector into a 2D column vector explicitly required for linear algebra.
#
# Requirements:
# 1. Initialize a simple flat bias vector: `bias = np.array([0.5, -1.2, 3.4])` (Shape is (3,)).
# 2. Reshape `bias` into an explicit column vector layout of shape (3, 1).
# 3. Print the new array and verify its `.ndim` has increased from 1 to 2.
# ==============================================================================================

# Write your solution in a new cell below this one

In [27]:
import numpy as np

bias = np.array([0.5, -1.2, 3.4])
bias.reshape(3,1)
print(bias)
print(bias.ndim)

[ 0.5 -1.2  3.4]
1


In [20]:
# ==============================================================================================
# QUESTION 10: Memory Identity Checking (Flatten vs. Ravel)
# ----------------------------------------------------------------------------------------------
# Task: Explore memory efficiency by comparing data copies versus reference views.
#
# Requirements:
# 1. Create a 2x2 matrix: `A = np.array([[10, 20], [30, 40]])`
# 2. Generate two unrolled vectors from `A`:
#    - `flat_vec` using `.flatten()`
#    - `ravel_vec` using `.ravel()`
# 3. Modify the first element of `flat_vec` to 999. Print `A` to check if the original matrix changed.
# 4. Modify the first element of `ravel_vec` to 888. Print `A` to check if the original matrix changed.
# 5. Add a comment explaining which method creates a real copy and which creates a zero-copy memory view.
# ==============================================================================================

# Write your solution in a new cell below this one

In [22]:
A = np.array([[10, 20], [30, 40]])
flat_vec= A.flatten()
ravel_vec= A.flatten()
flat_vec[0]=999
print(A)
flat_vec[0]=888
print(A)


[[10 20]
 [30 40]]
[[10 20]
 [30 40]]
