## Practical Exercises: Array Initializers, Shape Analysis, and Reshaping

### Directions
1. Insert a new code cell directly below each question block.
2. Write your programmatic solution inside that new cell.
3. Verify that your code executes cleanly without runtime dimension mismatch errors.

In [1]:
# ==============================================================================================
# QUESTION 1: Matrix Blank Canvas Initialization
# ----------------------------------------------------------------------------------------------
# Task: Create a 5x5 matrix filled entirely with zeros, then change the central element to 1.
#
# Requirements:
# 1. Initialize a 2D NumPy array named `canvas` of shape (5, 5) using `np.zeros`.
# 2. Use explicit 2D indexing to modify the exact middle element (row index 2, column index 2) to 1.0.
# 3. Print the matrix and verify its shape using `.shape`.
# ==============================================================================================

# Write your solution in a new cell below this one

In [2]:
%pip install numpy


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

canvas= np.zeros(shape=(5,5))
canvas[2][2]=1
print(canvas,f"\n shape is: {canvas.shape}")


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]] 
 shape is: (5, 5)


In [4]:
# ==============================================================================================
# QUESTION 2: Normal Distribution Variance Verification
# ----------------------------------------------------------------------------------------------
# Task: Generate random numbers from a standard normal distribution and inspect its properties.
#
# Requirements:
# 1. Generate a 2D tensor of shape (50, 50) containing random numbers with mean=0 and std=1.
#    (Hint: use `np.random.randn`).
# 2. Compute and print the empirical mean using `.mean()`.
# 3. Compute and print the empirical standard deviation using `.std()`.
# 4. Write a brief comment explaining why the printed mean is close to, but not exactly, 0.0.
# ==============================================================================================

# Write your solution in a new cell below this one

In [5]:
import numpy as np

a= np.random.randn(50,50)
print(f"Mean: {a.mean()}")
print(f"Standard Deviation: {a.std()}")


Mean: 0.003412560070991249
Standard Deviation: 0.9973590596193125


In [6]:
# ==============================================================================================
# QUESTION 3: Even Interval Generation via linspace
# ----------------------------------------------------------------------------------------------
# Task: Generate an array of evenly spaced numbers acting as thresholds between 0 and 5.
#
# Requirements:
# 1. Use `np.linspace` to create an array named `thresholds` containing exactly 11 elements 
#    equally dividing the range from 0.0 to 5.0 (inclusive).
# 2. Print the array.
# 3. Print the distance between any two adjacent elements to confirm the spacing is perfectly linear.
# ==============================================================================================

# Write your solution in a new cell below this one

In [7]:
import numpy as np

thresholds = np.linspace(start= 0.0,stop=5.0, num=11)
print(thresholds)
print(f"Spaces= {thresholds.std()}")
print(f"Spaces bw first two elements= {thresholds[1]-thresholds[0]}")
print(f"Spaces bw second two elements= {thresholds[2]-thresholds[1]}")


[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
Spaces= 1.5811388300841898
Spaces bw first two elements= 0.5
Spaces bw second two elements= 0.5


In [8]:
# ==============================================================================================
# QUESTION 4: Mathematical Elements Volume Audit
# ----------------------------------------------------------------------------------------------
# Task: Extract structural size attributes from a high-dimensional machine learning tensor.
#
# Requirements:
# 1. Initialize a 4D random uniform tensor named `activation_map` with shape (16, 3, 32, 32).
# 2. Print its total number of axes using `.ndim`.
# 3. Print its total element count volume using `.size`.
# 4. Programmatically calculate and print the expected size by multiplying the shape dimensions together.
# ==============================================================================================

# Write your solution in a new cell below this one

In [9]:

activation_map= np.random.rand(16,3,32,32)
print(f"total number of axes: {activation_map.ndim}")
print(f"total element count volume: {activation_map.size}")
print(f"size: {16*3*32*32}")

total number of axes: 4
total element count volume: 49152
size: 49152


In [10]:
# ==============================================================================================
# QUESTION 5: Reshaping Safety Laws & Total Count Invariance
# ----------------------------------------------------------------------------------------------
# Task: Intentionally trigger a common shape allocation mistake to understand how NumPy protects memory.
#
# Requirements:
# 1. Create a 1D vector containing numbers from 1 to 12 using `np.arange`.
# 2. Use a `try-except` code block to attempt reshaping this 12-element vector into a 3x5 matrix.
# 3. Catch the `ValueError` runtime exception and print the exact error message generated by NumPy.
# 4. Inside the same block, successfully reshape it into a valid 3x4 matrix and print the outcome.
# ==============================================================================================

# Write your solution in a new cell below this one

In [11]:
#out of syllabus

In [12]:
# ==============================================================================================
# QUESTION 6: Automatic Dimension Calculation with Wildcard -1
# ----------------------------------------------------------------------------------------------
# Task: Use NumPy's automated dimension solving feature to reshape a flat image sequence.
#
# Requirements:
# 1. Create a large flat vector of 1000 random pixel values.
# 2. Reshape this vector into a 2D matrix where you explicitly set the row dimension to 40, 
#    and pass `-1` as the column dimension.
# 3. Print the resulting array shape and write a short comment explaining how NumPy calculated 
#    the hidden column dimension.
# ==============================================================================================

# Write your solution in a new cell below this one

In [13]:
v= np.random.rand(1000)
v.reshape(40,-1)
print(f"shape: {v.shape}")

shape: (1000,)


In [14]:
# ==============================================================================================
# QUESTION 7: The Flatten vs. Transpose Ordering Trap
# ----------------------------------------------------------------------------------------------
# Task: Examine how row-major structuring alters data layout ordering during unrolling.
#
# Requirements:
# 1. Manually build this specific 2x3 matrix:
#    M = np.array([[1, 2, 3], 
#                  [4, 5, 6]])
# 2. Run `.flatten()` directly on `M` and print the result.
# 3. Run `.flatten()` on its transpose `M.T` and print the result.
# 4. Write a comment stating whether the outputs match and why the order changed.
# ==============================================================================================

# Write your solution in a new cell below this one

In [15]:
M = np.array([[1, 2, 3], 
                  [4, 5, 6]])
print(M.flatten())
print(M.T.flatten())
# the outputs wont match because when we transpose the rows and columns of a matrix interchanges therefore 
# the order of the flattened matrix changes


[1 2 3 4 5 6]
[1 4 2 5 3 6]


In [16]:
# ==============================================================================================
# QUESTION 8: Multi-Channel Tensor Unrolling
# ----------------------------------------------------------------------------------------------
# Task: Take a mock 3D image block representation and flatten it without modifying the original array.
#
# Requirements:
# 1. Construct a mock image tensor of shape (3, 4, 4) filled with random integers between 0 and 9.
#    (3 color channels, 4x4 spatial pixel resolution).
# 2. Unroll this multi-dimensional array into a simple continuous 1D line using `.flatten()`.
# 3. Print the shape of the flattened array.
# 4. Print the shape of the original tensor to prove that flattening creates a transformation 
#    without destroying the original tensor layout geometry.
# ==============================================================================================

# Write your solution in a new cell below this one

In [17]:
images= np.random.randint(0,9,size= (3,4,4))
images.flatten()
print(f"shape: {images.shape}")
print("shape of original shape: (3,4,4)")

shape: (3, 4, 4)
shape of original shape: (3,4,4)


In [18]:
# ==============================================================================================
# QUESTION 9: Creating Column Vectors for Weight Calculations
# ----------------------------------------------------------------------------------------------
# Task: Turn a standard flat 1D vector into a 2D column vector explicitly required for linear algebra.
#
# Requirements:
# 1. Initialize a simple flat bias vector: `bias = np.array([0.5, -1.2, 3.4])` (Shape is (3,)).
# 2. Reshape `bias` into an explicit column vector layout of shape (3, 1).
# 3. Print the new array and verify its `.ndim` has increased from 1 to 2.
# ==============================================================================================

# Write your solution in a new cell below this one

In [19]:
import numpy as np

bias = np.array([0.5, -1.2, 3.4])
bias.reshape(3,1)
print(bias)
print(bias.ndim)

[ 0.5 -1.2  3.4]
1


In [20]:
# ==============================================================================================
# QUESTION 10: Memory Identity Checking (Flatten vs. Ravel)
# ----------------------------------------------------------------------------------------------
# Task: Explore memory efficiency by comparing data copies versus reference views.
#
# Requirements:
# 1. Create a 2x2 matrix: `A = np.array([[10, 20], [30, 40]])`
# 2. Generate two unrolled vectors from `A`:
#    - `flat_vec` using `.flatten()`
#    - `ravel_vec` using `.ravel()`
# 3. Modify the first element of `flat_vec` to 999. Print `A` to check if the original matrix changed.
# 4. Modify the first element of `ravel_vec` to 888. Print `A` to check if the original matrix changed.
# 5. Add a comment explaining which method creates a real copy and which creates a zero-copy memory view.
# ==============================================================================================

# Write your solution in a new cell below this one

In [21]:
A = np.array([[10, 20], [30, 40]])
flat_vec= A.flatten()
ravel_vec= A.flatten()
flat_vec[0]=999
print(A)
flat_vec[0]=888
print(A)


[[10 20]
 [30 40]]
[[10 20]
 [30 40]]


## Practical Exercises: NumPy Dimensions, Slicing, and Basic Mathematical Operations

### Directions
1. Insert a new code cell directly below each question block.
2. Implement your programmatic solution using vectorized NumPy operations (avoid explicit Python loops).
3. Confirm your array mutations track perfectly with the specified target tensor shapes.

In [22]:
# ==============================================================================================
# QUESTION 1: Tracking Structural Statistics (min, max, mean, sum)
# ----------------------------------------------------------------------------------------------
# Task: Take a 1D vector of raw metrics and extract global computational properties.
#
# Requirements:
# 1. Initialize a flat 1D NumPy array named `scores` containing these exact values: [12, 45, 7, 23, 89, 34].
# 2. Use native NumPy array methods to calculate and print:
#    - The absolute minimum value using `.min()`
#    - The absolute maximum value using `.max()`
#    - The arithmetic average using `.mean()`
#    - The global total sum using `.sum()`
# ==============================================================================================

# Write your solution in a new cell below this one

In [23]:
# ==============================================================================================
# QUESTION 2: Understanding Vectorized Execution speed
# ----------------------------------------------------------------------------------------------
# Task: Demonstrate how NumPy eliminates standard sequential loops via element-wise transformations.
#
# Requirements:
# 1. Given a raw sample array: `inputs = np.array([1.0, 2.0, 3.0, 4.0])`
# 2. Apply the mathematical transformation formula $y = \sqrt{x} + 10$ to the entire array 
#    simultaneously using `np.sqrt()`. Do not use a `for` loop.
# 3. Print the final calculated output array.
# ==============================================================================================

# Write your solution in a new cell below this one

In [24]:
# ==============================================================================================
# QUESTION 3: Logits Exponential Normalization Check (Softmax Prep)
# ----------------------------------------------------------------------------------------------
# Task: Calculate the numeric numerators required for probability distribution models.
#
# Requirements:
# 1. Create a 1D array named `logits` containing the values: [-1.0, 0.0, 2.0, 4.0].
# 2. Use `np.exp()` to apply Euler's exponential function element-wise across the array.
# 3. Print the resulting transformed vector and observe how negative values scale toward zero.
# ==============================================================================================

# Write your solution in a new cell below this one

In [25]:
# ==============================================================================================
# QUESTION 4: Extracting Vertical Column Reductions via axis=0
# ----------------------------------------------------------------------------------------------
# Task: Compress the row dimension of a 2D feature grid to find individual column sums.
#
# Requirements:
# 1. Manually build the following 3x2 matrix:
#    data_grid = np.array([[1, 10], 
#                          [2, 20], 
#                          [3, 30]])
# 2. Compute the total sum along `axis=0` and store it in a variable named `column_totals`.
# 3. Print `column_totals` and verify its shape changes from a 2D layout to a flat 1D shape (2,).
# ==============================================================================================

# Write your solution in a new cell below this one

In [26]:
# ==============================================================================================
# QUESTION 5: Extracting Horizontal Averages via axis=1
# ----------------------------------------------------------------------------------------------
# Task: Calculate individual sample averages across row sequences.
#
# Requirements:
# 1. Initialize a 2x3 matrix containing random floating point values using `np.random.rand(2, 3)`.
# 2. Compute the mathematical mean across columns by setting `axis=1`.
# 3. Print the resulting mean array and verify that your output contains exactly 2 values.
# ==============================================================================================

# Write your solution in a new cell below this one

In [27]:
# ==============================================================================================
# QUESTION 6: Index Tracking via argmax() for Multi-Class Prediction
# ----------------------------------------------------------------------------------------------
# Task: Track down the spatial coordinate index representing the high-confidence winning class.
#
# Requirements:
# 1. Suppose a model outputs this confidence distribution for 3 specific classes:
#    probabilities = np.array([0.15, 0.72, 0.13])
# 2. Use `np.argmax()` to programmatically extract the integer position index holding the highest value.
# 3. Print the winning index (the expected answer is 1).
# ==============================================================================================

# Write your solution in a new cell below this one

In [28]:
# ==============================================================================================
# QUESTION 7: Spatial Bounding Box Video Slicing
# ----------------------------------------------------------------------------------------------
# Task: Isolate a specific top-left $2 \times 2$ pixel region from an image data grid.
#
# Requirements:
# 1. Build a 4x4 matrix representing a simple grayscale canvas using `np.arange(16).reshape(4, 4)`.
# 2. Use multi-dimensional slicing syntax (`[row_slice, col_slice]`) to extract the sub-matrix 
#    occupying the first two rows and the first two columns.
# 3. Print the resulting 2x2 cropped canvas.
# ==============================================================================================

# Write your solution in a new cell below this one

In [29]:
# ==============================================================================================
# QUESTION 8: Channel Extraction from an Image Batch Tensor
# ----------------------------------------------------------------------------------------------
# Task: Isolate individual color planes out of high-dimensional deep learning arrays.
#
# Requirements:
# 1. Generate a mock random image batch tensor of shape (2, 3, 8, 8). 
#    (2 images, 3 color channels, 8x8 resolution grid).
# 2. Using slicing, extract all image batches, but isolate only the Green color channel (index 1).
# 3. Print the shape of your sliced array and verify it is exactly (2, 8, 8).
# ==============================================================================================

# Write your solution in a new cell below this one

In [30]:
# ==============================================================================================
# QUESTION 9: Spatial Image Resolution Striding (Downsampling)
# ----------------------------------------------------------------------------------------------
# Task: Skip intermediate coordinate cells using step-slicing strides to downsample data.
#
# Requirements:
# 1. Create an 8x8 matrix filled with sequential integers from 0 to 63.
# 2. Use step striding syntax (`::step`) on both axes to pull out every second row and column.
# 3. Print the resulting shape and verify that the resolution scales down down to a 4x4 grid.
# ==============================================================================================

# Write your solution in a new cell below this one

In [31]:
# ==============================================================================================
# QUESTION 10: Dynamic Vector Re-Dimensioning via -1 Wildcards
# ----------------------------------------------------------------------------------------------
# Task: Unroll a multi-dimensional matrix layout into a column vector while leaving 
#       dimension calculations to NumPy.
#
# Requirements:
# 1. Establish a 2D matrix: `features = np.array([[5, 10], [15, 20], [25, 30]])` (Shape: (3,2)).
# 2. Reshape this matrix into an explicit 2D column profile using `.reshape(-1, 1)`.
# 3. Print the mutated matrix shape and confirm it matches a valid column layout of (6, 1).
# ==============================================================================================

# Write your solution in a new cell below this one